### ISSUE TITLE
Latest update has broken primary menu (simple site, no mods of any kind)

### ISSUE THREAD

**Issue by addario-br** [godaddy-wordpress/go#458]
Hi folks,

Great theme you got here! I've just used it to provide a portal to our small Scottish village as a donation to our community association. Here: www.new-deer.com

It was working wonderfully until I just updated it and now the primary menu won't work where there are sub-items.  The first row of menu entries work but any nested pages won't. You don't even get a mouse-over "link" hand when you open the menu.

A introduced bug?

Any assistance would be greatly appreciated. 

Thanks!

**Comment by addario-br** [comment]
Update: The menu's work as expected on this page: http://new-deer.com/?s=

So whatever has been broken does not affect the Search page at all.

**Comment by richtabor** [comment]
I think this has been resolved in the recent #449 PR.

**Comment by addario-br** [comment]
> I think this has been resolved in the recent #449 PR.

That's great to hear! I've updated it on WordPress itself but it seems to be broken still, is there a way to update to #449 PR? Excuse my ignorance as I'm not particularly versed on this.

**Comment by addario-br** [comment]
Hi folks. So I downloaded the Zip folder of the latest version of Go here from GitHub and installed that instead of the version you can download from within WordPress itself but still no go, same issue.

Any suggestions on how to downgrade to an earlier version which does not have this issue?

**Comment by addario-br** [comment]
Some progress!

I figured out that the issue lies not on the theme's CSS but on this file: /wp-includes/css/dist/block-library/style.min.css?ver=5.3.2

More specifically here:

.wp-block-cover-image .wp-block-cover__inner-container, .wp-block-cover .wp-block-cover__inner-container

and here:

.wp-block-cover-image.has-background-dim:before, .wp-block-cover.has-background-dim:before

On those entries if I change the **z-index: 1;** to = 0 then the menu works perfectly again.

My only problem is that i can't permanently edit the /wp-includes/css/dist/block-library/style.min.css file because of limitations of my hosting platform so I now need to figure out another way around it.

**Comment by richtabor** [comment]
Thanks for digging into this @addario-br - we'll take a closer look and get this in the next release.

**Comment by richtabor** [comment]
I confirmed that this is resolved by #449. @addario-br, you may install the latest build of the theme ([from here](https://github.com/godaddy-wordpress/go/releases/tag/canary)) to try it out.
