### ISSUE TITLE
Setting the blog page to display excerpts also causes single posts to display the excerpt

### ISSUE THREAD

**Issue by GaryBarrettDev** [godaddy-wordpress/go#583]
**Describe the bug:**

In Appearance > Customize > Site Settings, enable "Blog Excerpts".

Then check any single post.

Instead of displaying the full post, it'll display an excerpt.

Checked in version 1.3.6

**Expected behavior:**

Single posts should always display the full content.

**Priority** (select one):
- [ ] High - Functional blocker
- [x] Medium - Doesn't work as expected 
- [ ] Low - Not a big deal but we'd want to get to this eventually

**Comment by sarahjunefox** [comment]
Hi, I was wondering when you expect to pick this up? It is a blocker for launchin my website.

**Comment by andersbea** [comment]
Hi,
I was also having this issue. I fixed the issue temporarily by changing the theme code, but would prefer a supported solution. 

For those who want to fix it temporarily simply need to add an additional check in the content.php which you can find in "Appearance>Theme Editor>Theme Files>partials>content.php". Simply add the "is_home()" check to verify if you are in the blog page. The related part of the section should look like this:

```php

		<div class="content-area entry-content">
			<?php
			if ( is_search() || ( get_theme_mod( 'blog_excerpt', false ) && is_home() ) ) {
				the_excerpt();
			} else {
				the_content();
			}
```

**Comment by andersbea** [comment]
I have now created a pull request with the suggested fix above. Hopefully they accept it and push the change soon. See pull request: #591

**Comment by sarahjunefox** [comment]
It looks like there was activity on the pull request but this issue is still happening on my site, can you check it please?
http://babyfrank.co/

**Comment by EvanHerman** [comment]
This has been resolved and has been merged into production. See https://github.com/godaddy-wordpress/go/pull/591
